### ISSUE TITLE
Reorganização do Unity-Learn

### ISSUE THREAD

**Issue by caioteixeira** [Unity-Brazil/Unity-Learn#2]
Vou falar em Português mesmo, porque acho que boa parte dos contribuidores e usuários desse repositórios são brasileiros.
Eu acho que devemos pensar seriamente em reorganizar as seções desse repositório, acho que está muito desorganizado e pouco intuitivo. Minha ideia é categorizar os tutoriais como o excelente Awesome-Unity faz com os assets (https://github.com/RyanNielson/awesome-unity). O que acham?
Obs: Posso cuidar dessa reorganização, só para ver a opinião de todos mesmo.

**Comment by cesardeazevedo** [comment]
Boa Caio, realmente as seções ficaram confusas, o awesome-unity é bem bacana, manda ve ai. :+1:

**Comment by caioteixeira** [comment]
Beleza. Vou cuidar disso no meu fork na semana que vem, depois subo um pull request para vocês olharem antes de dar merge.

**Comment by caioteixeira** [comment]
Pronto, já fiz e acabei de dar merge. Peguei todos os itens que já tínhamos na lista e categorizei.
Agora é só tentarmos adicionar mais materiais com o tempo.

**Comment by cesardeazevedo** [comment]
Ficou SHOW, eu colocaria a parte de `ScriptableObjects` na parte de `Serializations`, que são quase a mesma coisa, e trocaria de `Unsupported Programming Languages` para `Alternative Programming Languages`, o resto esta perfeito, essa semana eu adiciono mais links também...

Muito Obrigado Caio.

**Comment by caioteixeira** [comment]
Boa, vou alterar isso
